### ISSUE TITLE
Post Start Temperature Error

### ISSUE THREAD

**Issue by FrederikNT** [horemansp/HUUM#1]
I am trying to start my sauna according to the description in Node Red with a HTTP request but get following error: "Error 400. Invalid targetTemperature".

The description says: "api.huum.eu/action/home/start?tartetTemperature=80" where I assume "tartet" is a typo and should be "api.huum.eu/action/home/start?targetTemperature=80". But even with that I get the same error.

Get command works fine :)

**Comment by ckossendey** [comment]
Hi Frederik, i was struggling with this command via iobroker today - it is a bit weird. In Node Red i got running a few month ago via this flow: `[{"id":"3c0992c4.fcae8e","type":"inject","z":"418d6c5a.64c9c4","name":"query parameter","props":[{"p":"payload","v":"Sauna Start manuell","vt":"str"},{"p":"topic","v":"","vt":"string"}],"repeat":"","crontab":"","once":false,"onceDelay":"","topic":"","payload":"Sauna Start manuell","payloadType":"str","x":240,"y":980,"wires":[["4639576.c547ca8"]]},{"id":"4639576.c547ca8","type":"function","z":"418d6c5a.64c9c4","name":"","func":"var temp = global.get('targettemp');\nmsg.headers = {};\nmsg.headers={Authorization: 'user:pass' }\n\nmsg.payload={targetTemperature: temp};\n\nreturn msg","outputs":1,"noerr":0,"initialize":"","finalize":"","x":550,"y":980,"wires":[["54e142dc.eca14c","2fdda3a7.1e35dc"]]},{"id":"2fdda3a7.1e35dc","type":"http request","z":"418d6c5a.64c9c4","name":"","method":"POST","ret":"obj","paytoqs":"ignore","url":"https://api.huum.eu/action/home/start","tls":"","persist":false,"proxy":"","authType":"basic","x":750,"y":980,"wires":[["dda9818c.f3801"]]}]`

Cheers

**Comment by FrederikNT** [comment]
Wow many thanks ck that was a fast response! Gona try later

Cheers & Vielen Dank ;)

**Comment by FrederikNT** [comment]
Ck thanks again. Just tested it and it is working nicely. Time for a sauna session now ;)
